### PR TITLE
[Meta] improve codeflow.yml and dockerfile

### PR DESCRIPTION
**Pull request by grahamjenson**

### CODE REVIEW

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1 | Message
------------ | ------------- | ----------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/step&ref=4eb17ea0519bde07396bfac5fab322c7fc7db7c6)

**Comment by heimdall-asguard** [comment]
Review Error for lian@2018-05-22T15:37:34+00:00
User failed mfa authentication

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
lian | 1 | approved 



[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/step&ref=4eb17ea0519bde07396bfac5fab322c7fc7db7c6)

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
lian | 1 | approved 

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/step&ref=684aca80d653606ab1858247b46234c8983a385b)

**Comment by brad-larson** [comment]
+1

**Comment by heimdall-asguard** [comment]
Reviews      | 2/1 | Message
------------ | ------------- | ----------
lian | 1 | approved 
brad-larson | 1 | +1 



[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/step&ref=4eb17ea0519bde07396bfac5fab322c7fc7db7c6)

**Pull request merged**
