### PR TITLE
[Fix] Adding SecondsPath to the Wait State

### PR DESCRIPTION
**Pull request by grahamjenson**

### CODE REVIEW

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1
------------ | -------------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/step&ref=28c11c60d32313855d18baa5c75956d3aee33007)

**Comment by brad-larson** [comment]
+1

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1
------------ | -------------
brad-larson | 1

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/step&ref=28c11c60d32313855d18baa5c75956d3aee33007)

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1
------------ | -------------
brad-larson | 1

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/step&ref=b7adaf06aadf6cf65300229899f77b85f216015f)

**Pull request merged**
